title = "Rob Brazier"
baseURL = "/"
languageCode = "en-gb"
theme = "sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Rob Brazier"
  description = "The personal website of Rob Brazier"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "RobBrazier"
  Email         = "m%65%40ro%62%2e%62r%61z%69%65r%2ec%6coud"
  Twitter       = "robbrazier_"
  LinkedIn      = "robbrazier1"
  #Stackoverflow = "username"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
# [[menu.main]]
#   name = "resume"
#   identifier = "resume"
#   weight = 300
#   url = "/resume/"
