baseURL = "/"
languageCode = "en-gb"
title = "robbrazier.com"
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 2
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 3
[params]
author = "Rob Brazier"
copyright = "&copy; Rob Brazier. Powered by [Hugo](https://gohugo.io/)"
disqusShortName = "robbrazier-com"
siteName = "Rob Brazier"
