baseURL: "/"
languageCode: "en-gb"
title: "Rob Brazier"
copyright: "&copy; Rob Brazier"
menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 1
    - identifier: "projects"
      name: "Projects"
      url: "/projects/"
      weight: 2
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 3
author:
  name: "Rob Brazier"
params:
  author: "Rob Brazier"
  
markup:
  goldmark:
    renderer:
      unsafe: true