baseURL: "https://www.robbrazier.com"
title: Rob Brazier
theme: maverick
languageCode: en

author:
  name: Rob Brazier

params:
  author: Rob Brazier
  info: Software Engineer
  avatarUrl: /images/avatar.jpg
  favicon_16: /img/favicon-16x16.png
  favicon_32: /img/favicon-32x32.png
  touchicon: /img/apple-touch-icon.png
  colorScheme: auto
  social:
    #    - name: twitter
    #      url: 'https://twitter.com/robbrazier_'
    #      icon: fa fa-twitter fa-2x
    - name: github
      url: "https://github.com/robbrazier"
      icon: fa fa-github fa-2x
    - name: codeberg
      url: "https://codeberg.org/RobBrazier"
      icon: fa fa-gitea fa-2x
  csp:
    childsrc:
      - "'self'"
    fontsrc:
      - "'self'"
    formaction:
      - "'self'"
    framesrc:
      - "'self'"
    imgsrc:
      - "'self'"
      - "d33wubrfki0l68.cloudfront.net"
      - "cdn.usefathom.com"
    objectsrc:
      - "'none'"
    stylesrc:
      - "'self'"
      - "'unsafe-inline'"
    scriptsrc:
      - "'self'"
      - "'unsafe-inline'"
      - "plausible.io"
      - "cdn.usefathom.com"
    prefetchsrc:
      - "'self'"
    connectsrc:
      - "'self'"
      - "plausible.io"
      - "cdn.usefathom.com"

menu:
  main:
    - name: Posts
      url: /posts

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

module:
  mounts:
    - source: assets
      target: static

server:
  headers:
    - for: /**
      values:
        x-content-type-options: nosniff
        x-frame-options: deny
        x-xss-protection: 1; mode=block
        referrer-policy: strict-origin-when-cross-origin
