baseURL = "/"
languageCode = "en-gb"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  siteName = "Rob Brazier"
  author = "Rob Brazier"
  copyright = "&copy; Rob Brazier. Powered by [Hugo](https://gohugo.io/)"

disqusShortName = "robbrazier-com"

## Main Menu
[[menu.main]]
  name = "posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"