# title = "Rob Brazier"
baseURL = "/"
languageCode = "en-gb"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  author = "Rob Brazier"

## Main Menu
[[menu.main]]
  name = "posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"