app = 'robbrazier-com'
primary_region = 'lhr'

[build.args]
BASE_URL = "https://robbrazier.com"

[deploy]
strategy = "rolling"

[env]
SERVER_LOG_LEVEL = "info"
SERVER_IGNORE_HIDDEN_FILES = "true"
SERVER_LOG_REMOTE_ADDRESS = "true"
SERVER_PORT = "3000"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']
[http_service.concurrency]
hard_limit = 500
soft_limit = 450
#[[http_service.checks]]
#grace_period = '1s'
#interval = '10s'
#method = 'GET'
#timeout = '1s'
#path = '/health'

[[vm]]
size = 'shared-cpu-1x'

[[statics]]
guest_path = '/public/css'
url_prefix = '/css'

[[statics]]
guest_path = '/public/images'
url_prefix = '/images'

[[statics]]
guest_path = '/public/img'
url_prefix = '/img'
