baseURL = 'https://robbrazier.com'
languageCode = 'en-gb'
title = 'Rob Brazier'
enableRobotsTXT = true


[params]
items = 20

[params.author]
name = 'Rob Brazier'

[params.services]
[params.services.umami_analytics]
id = "193b303e-85fd-4e0d-980d-41c2f569ae7f"
script_url = "https://psychic-couscous.b-cdn.net/script.js"

[outputs]
home = ['html']
section = ['html', 'rss']
taxonomy = ['html']
term = ['html']

[menus]
[[menus.main]]
name = 'Posts'
url = '/posts'

[minify]
minifyOutput = true

[module]
[[module.imports]]
path = "github.com/hugomods/icons/vendors/simple-icons"
[[module.imports]]
path = "github.com/hugomods/umami-analytics"
[[module.imports]]
path = "github.com/hugomods/images"
