---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: index.md
  label: Homepage
- type: directory
  path: projects
  label: Projects
  create: documents
  match: "*.md"
  templates:
  - project
- type: directory
  path: posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
upload_dir: media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm ci
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  instant_preview_command: npm run-script start
