---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Homepage
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
  exclude: _index.md
- type: directory
  path: content/posts
  label: Posts
  create: documents
  match: "*"
  exclude: _index.md
upload_dir: assets/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.49.2
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node10
  mount_path: "/srv"
  instant_preview_command: npm run assets && hugo server -D -E -F --port 8080 --bind
    0.0.0.0 --renderToDisk -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.49.2
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.49.2
