pipeline:
  branch:
    image: lucap/drone-netlify
    token: $NETLIFY_TOKEN
    site_id: $SITE_ID
    environment: branch-deploy
    when:
      branch:
        exclude: [ master ]
  
  pull-request:
    image: lucap/drone-netlify
    token: $NETLIFY_TOKEN
    site_id: $SITE_ID
    environment: deploy-preview
    when:
      event: [ pull_request ]
  
  deploy:
    image: lucap/drone-netlify
    token: $NETLIFY_TOKEN
    site_id: $SITE_ID
    environment: production
    when:
      branch:
        include: [ master ]