when:
  - branch: main
    event: push

steps:
  - name: build
    image: ghcr.io/gohugoio/hugo:v0.161.1
    when:
      - event: push
    environment:
      BASE_URL: https://robbrazier.com
    commands:
      - hugo build --gc -b $BASE_URL
  - name: deploy
    image: node:lts-alpine
    when:
      - event: push
    environment:
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: CLOUDFLARE_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_WORKERS_API_TOKEN
    commands:
      - npx -y wrangler deploy 
