name: Deploy

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@v1.6.1
        with:
          git_remote_url: "ssh://dokku@$DOKKU_HOST:22/$DOKKU_APPNAME"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
